[project]
name = "bog-standard-project"
version = "0.1.0"
description = "A simple greeting module."
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
